require 'minitest/autorun'
require 'minitest-spec-rails/init/active_support'
require 'minitest-spec-rails/init/mini_shoulda'
require 'minitest-spec-rails/init/action_view'
require 'minitest-spec-rails/init/action_controller'
require 'minitest-spec-rails/init/action_dispatch'
require 'minitest-spec-rails/init/action_mailer'
